version: "3.9"
services:
  jupyter:
    build:
      dockerfile: Dockerfile
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_PORT=7777
    sysctls:
      - net.ipv4.tcp_keepalive_time=60
    ports:
      - "7777:7777"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./.env:/home/jovyan/notebooks/.env
